# 20220318
# BJL
# X vs Y reads
# infer sex of each embryo


#packages
library(tidyverse)
library(lubridate)



# directories
dataDir <- "/camp/lab/turnerj/working/Bryony/manuscript/analysis/data/bs_stats"
plotDir <- "/camp/lab/turnerj/working/Bryony/manuscript/analysis/plots"
sampleDir <- "/camp/lab/turnerj/working/Bryony/manuscript/analysis/data"

#get sample metadata
setwd(sampleDir)
sampledata <- read.delim(file = "PM18153_sample_data.txt") 

# import reads per chromosome datafile
# input file was generated by script "QC_reads_per_chr.sh" 
# after, in bash, all output files were concatenated
# excel 'text to columns' and 'sort' were used to tidy data
setwd(dataDir)
chrReads <- read_delim(file = "reads_per_chr_all.txt", delim = "\t",
                       col_names = c("sample_id", "chr", "reads")) %>%
  filter(sample_id %in% sampledata$sample_id[sampledata$include_in_analysis == "include"])
  

# calculate total reads per sample
chrReadsTotal <- chrReads %>% group_by(sample_id) %>%     
  mutate(total = sum(reads)) %>%
  mutate(percReads = (reads/total)*100)                   


# add sample timepoint
chrReadsTotal <- chrReadsTotal %>%
  left_join(select(sampledata,
                   sample_design_char,
                   sample_id),
            by = "sample_id")

# plot
setwd(plotDir)

# for plot labels
stage_labs <- c("sperm" = "sperm",
                "oocyte" = "oocyte",
                "1.5_embryo" = "E1.5",
                "2.5_embryo" = "E2.5",
                "3.5_embryo" = "E3.5",
                "4.5_embryo" = "E4.5",
                "5.5_embryo" = "E5.5",
                "6.5_embryo" = "E6.5",
                "7.5_embryo" = "E7.5",
                "7.5_ED" = "E7.5 ED",
                "7.5_TE" = "E7.5 TE")

# for plot colours
cols <- c("#9467BD",
          "#BCBD22",
          "#AEC7E8",
          "#98DF8A",
          "#DBDB8D",
          "#FFBB78",
          "#FF9896",
          "#E377C2",
          "#D62728",
          "#8C564B",
          "#C49C94")


plotdat <- chrReadsTotal %>%
  dplyr::select(sample_id, chr,
                percReads, sample_design_char) %>%
  filter(chr == "chrX" | chr == "chrY") %>% 
  spread(key = chr, value = percReads) %>%
  mutate(sample_design_factor = factor(sample_design_char,
                        levels = c("sperm", "oocyte",
                                   "1.5_embryo", "2.5_embryo", "3.5_embryo",
                                   "4.5_embryo", "5.5_embryo", "6.5_embryo",
                                   "7.5_embryo", "7.5_ED", "7.5_TE")))

# each sample stage a different colour
plotdat %>% ggplot(aes(x = chrX,
                    y = chrY,
                    colour = sample_design_factor))+
  geom_jitter(#width = 0.1,
              #height = 0.00001,
              size = 3)+
  xlab("% reads mapped to X chromosome")+
  ylab("% reads mapped to pseudoY chromosome")+
  scale_colour_manual(values = cols,
                      labels = stage_labs,
                      name = "sample stage")+
  theme_bw()+
  theme(axis.title.y = element_text(size = 20))+
  theme(axis.title.x = element_text(size = 20),
        axis.text = element_text(size = 16),
        legend.text = element_text(size = 16),
        legend.title = element_text(size = 20))
ggsave("XY_reads_sample_stage.pdf", useDingbats=FALSE, width = 9)

# export list of sample sex

females <- plotdat %>% filter(chrY < 0.0001) %>%
  dplyr::select(sample_id)

males <- plotdat %>% filter(chrY > 0.0001) %>%
  dplyr::select(sample_id)

females$sex <- rep("female", times=nrow(females))

males$sex <- rep("male", times=nrow(males))

sample_sex <- rbind(males, females)

setwd(dataDir)
write.table(sample_sex, file = paste0(today(),"_sample_sex.txt"))